# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

#æ·»åŠ æ–°èœå•é¡¹éµå¾ªä»¥ä¸‹è§„åˆ™
# menu:
#  link:               fontawesomeå›¾æ ‡ï¼Œçœç•¥å‰ç¼€ï¼Œæœ¬ä¸»é¢˜å‰ç¼€ä¸º icon-ï¼Œå¿…é¡»
#    text: About       èœå•æ˜¾ç¤ºçš„æ–‡å­—ï¼Œå¦‚æœçœç•¥å³é»˜è®¤ä¸å›¾æ ‡ä¸€è‡´ï¼Œé¦–å­—æ¯ä¼šè½¬å¤§å†™
#    url: /about       é“¾æ¥ï¼Œç»å¯¹æˆ–ç›¸å¯¹è·¯å¾„ï¼Œå¿…é¡»ã€‚
#    target: _blank    æ˜¯å¦è·³å‡ºï¼Œçœç•¥åˆ™åœ¨å½“å‰é¡µé¢æ‰“å¼€
menu:
  home:
    text: ä¸»é¡µ
    url: /
  archives:
    url: /archives
  categories:
    url: /categories
  tags:
    url: /tags
  celing:
    text: ä¾§è†
    url: http://bejond.org
  about:
    #text: å…³äº
    url: /about/index.html
  github:
    url: https://github.com/bejondshao
    target: _blank
  weibo:
    url: http://www.weibo.com/slbxts
    target: _blank
  #link:
    #text: æµ‹è¯•
    #url: /404

rss: /atom.xml

#ä½ çš„å¤´åƒurl
avatar: /img/logo1.png

#æ·»åŠ å›¾åƒç‚¹å‡»é“¾æ¥ï¼Œé»˜è®¤ä¸ºä¸»ç›®å½•ï¼Œå¯æ ¹æ®éœ€è¦ä¿®æ”¹aboutç­‰ç›®å½•
avatar_link: /

# email
email: a@bejond.org

# è®¾ç½® Android L Chrome æµè§ˆå™¨çŠ¶æ€æ é¢œè‰²
color: '#3F51B5'

# Content
tags:
  title: æ ‡ç­¾

# æ–‡ç« æˆªæ–­
excerpt_render: false
excerpt_length: 200
excerpt_link: é˜…è¯»å…¨æ–‡...
mathjax: false
archive_yearly: true

#æ˜¯å¦å¼€å¯åˆ†äº«
share: true

#æ˜¯å¦å¼€å¯æ‰“èµï¼Œå…³é—­ reward: false
reward:
  title: è°¢è°¢ä½ ç»™äºŒç‹—ä¹°ğŸ±ç²®
  wechat: /img/wechat.jpg     #å¾®ä¿¡ï¼Œå…³é—­è®¾ä¸º false
  alipay: false #/img/alipay.jpg     #æ”¯ä»˜å®ï¼Œå…³é—­è®¾ä¸º false

#æ˜¯å¦å¼€å¯æœç´¢
search: true

#æ˜¯å¦å¤§å±å¹•ä¸‹æ–‡ç« é¡µéšè—å¯¼èˆª
hideMenu: true

#æ˜¯å¦å¼€å¯toc
#toc: false
toc:
  list_number: true  # æ˜¯å¦æ˜¾ç¤ºæ•°å­—æ’åº

#ç«™é•¿ç»Ÿè®¡ï¼Œå¦‚è¦å¼€å¯ï¼Œè¾“å…¥CNZZç«™ç‚¹idï¼Œå¦‚ cnzz: 1255152447
cnzz: false

# Miscellaneous
# google_analytics: ''
favicon: /img/favicon.ico

# less
less:
  compress: true
  paths:
    - source/css/style.less

#æ˜¯å¦å¼€å¯å¤šè¯´è¯„è®ºï¼Œå¡«å†™ä½ åœ¨å¤šè¯´ç”³è¯·çš„é¡¹ç›®åç§° duoshuo: duoshuo-key
#è‹¥ä½¿ç”¨disqusï¼Œè¯·åœ¨åšå®¢configæ–‡ä»¶ä¸­å¡«å†™disqus_shortnameï¼Œå¹¶å…³é—­å¤šè¯´è¯„è®º
# duoshuo: 
